<div class="container">

<table style="width: 100%;"><tr>
<td>throw</td>
<td style="text-align: right;">R Documentation</td>
</tr></table>
<h2>Throws an exception</h2>

<h3>Description</h3>

<p>Throws an exception by calling stop().
</p>
<p>Note that <code>throw()</code> can be defined for specific classes, which can
then be caught (or not) using <code>tryCatch</code>().
</p>
<p><em>This default function will be overridden by ditto in the <b>R.oo</b>
package, if that is loaded.  The latter <code>R.oo::throw()</code> implementation
is fully backward compatible with this one, but the error object thrown
is of class <code>R.oo::Exception</code>.</em>
</p>
<p><em>WARNING: This function is deprecated in favor of <code>R.oo::throw()</code>,
or alternatively, just <code>stop()</code>.</em>
</p>


<h3>Usage</h3>

<pre><code class="language-R">## Default S3 method:
throw(...)
</code></pre>


<h3>Arguments</h3>

<table><tr style="vertical-align: top;">
<td><code>...</code></td>
<td>
<p>One or several strings that are concatenated and collapsed
into on message string.</p>
</td>
</tr></table>
<h3>Value</h3>

<p>Returns nothing.
</p>


<h3>Author(s)</h3>

<p>Henrik Bengtsson</p>


<h3>Examples</h3>

<pre><code class="language-R">rbern &lt;- function(n=1, prob=1/2) {
  if (prob &lt; 0 || prob &gt; 1)
    throw("Argument 'prob' is out of range: ", prob)
  rbinom(n=n, size=1, prob=prob)
}

rbern(10, 0.4)
# [1] 0 1 0 0 0 1 0 0 1 0
tryCatch({
  rbern(10, 10*0.4)
}, error=function(ex) {})
</code></pre>


</div>