<div class="container">

<table style="width: 100%;"><tr>
<td>Exception</td>
<td style="text-align: right;">R Documentation</td>
</tr></table>
<h2>The Exception class to be thrown and caught</h2>

<h3>Description</h3>

<p>Package:  R.oo <br><b>Class Exception</b><br></p>
<p><code>Object</code><br><code>~~|</code><br><code>~~+--</code><code>try-error</code><br><code>~~~~~~~|</code><br><code>~~~~~~~+--</code><code>condition</code><br><code>~~~~~~~~~~~~|</code><br><code>~~~~~~~~~~~~+--</code><code>error</code><br><code>~~~~~~~~~~~~~~~~~|</code><br><code>~~~~~~~~~~~~~~~~~+--</code><code>simpleError</code><br><code>~~~~~~~~~~~~~~~~~~~~~~|</code><br><code>~~~~~~~~~~~~~~~~~~~~~~+--</code><code>Exception</code><br></p>
<p><b>Directly known subclasses:</b><br>
InternalErrorException, RccViolationException, RdocException<br></p>
<p>public static class <b>Exception</b><br>
extends simpleError<br></p>
<p>Creates an Exception that can be thrown and caught. The <code>Exception</code>
class is the root class of all other <code>Exception</code> classes.
</p>


<h3>Usage</h3>

<pre><code class="language-R">Exception(..., sep="", collapse=", ")
</code></pre>


<h3>Arguments</h3>

<table>
<tr style="vertical-align: top;">
<td><code>...</code></td>
<td>
<p>One or several strings, which will be concatenated and contain
informative message about the exception.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>sep</code></td>
<td>
<p>The string to used for concatenating several strings.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>collapse</code></td>
<td>
<p>The string to used collapse vectors together.</p>
</td>
</tr>
</table>
<h3>Fields and Methods</h3>

<p><b>Methods:</b><br></p>

<table>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>as.character</code> </td>
<td style="text-align: left;"> Gets a character string representing of the Exception.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>getCall</code> </td>
<td style="text-align: left;">  -</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>getCalls</code> </td>
<td style="text-align: left;"> Gets the active calls saved when the exception was created.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>getLastException</code> </td>
<td style="text-align: left;"> Static method to get the last Exception thrown.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>getMessage</code> </td>
<td style="text-align: left;"> Gets the message of the Exception.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>getStackTrace</code> </td>
<td style="text-align: left;"> Gets the stack trace saved when the exception was created.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>getStackTraceString</code> </td>
<td style="text-align: left;"> Gets the stack trace as a string.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>getWhen</code> </td>
<td style="text-align: left;"> Gets the time when the Exception was created.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>print</code> </td>
<td style="text-align: left;"> Prints the Exception.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>printStackTrace</code> </td>
<td style="text-align: left;"> Prints the stack trace saved when the exception was created.</td>
</tr>
<tr>
<td style="text-align: right;">
 </td>
<td style="text-align: left;"> <code>throw</code> </td>
<td style="text-align: left;"> Throws an Exception that can be caught.</td>
</tr>
<tr>
<td style="text-align: right;">
</td>
</tr>
</table>
<p><b>Methods inherited from error</b>:<br>
as.character, throw
</p>
<p><b>Methods inherited from condition</b>:<br>
abort, as.character, conditionCall, conditionMessage, print
</p>
<p><b>Methods inherited from Object</b>:<br>
$, $&lt;-, [[, [[&lt;-, as.character, attach, attachLocally, clearCache, clearLookupCache, clone, detach, equals, extend, finalize, getEnvironment, getFieldModifier, getFieldModifiers, getFields, getInstantiationTime, getStaticInstance, hasField, hashCode, ll, load, names, objectSize, print, save
</p>


<h3>Author(s)</h3>

<p>Henrik Bengtsson</p>


<h3>See Also</h3>

<p>See also <code>tryCatch()</code> (and <code>try</code>()).
</p>


<h3>Examples</h3>

<pre><code class="language-R">
######################################################################
# 1. To catch a regular "error" exception thrown by e.g. stop().
######################################################################
x &lt;- NA
y &lt;- NA
tryCatch({
  x &lt;- log(123)
  y &lt;- log("a")
}, error = function(ex) {
  print(ex)
})
print(x)
print(y)



######################################################################
# 2. Always run a "final" expression regardless or error or not.
######################################################################
filename &lt;- tempfile("R.methodsS3.example")
con &lt;- file(filename)
tryCatch({
  open(con, "r")
}, error = function(ex) {
  cat("Could not open ", filename, " for reading.\n", sep="")
}, finally = {
  close(con)
  cat("The id of the connection is ",
       ifelse(is.null(con), "NULL", con), ".\n", sep="")
})


######################################################################
# 3. Creating your own Exception class
######################################################################
setConstructorS3("NegativeLogValueException", function(
  msg="Trying to calculate the logarithm of a negative value", value=NULL) {
  extend(Exception(msg=msg), "NegativeLogValueException",
    .value = value
  )
})

setMethodS3("as.character", "NegativeLogValueException", function(this, ...) {
  paste(as.character.Exception(this), ": ", getValue(this), sep="")
})

setMethodS3("getValue", "NegativeLogValueException", function(this, ...) {
  this$.value
})


mylog &lt;- function(x, base=exp(1)) {
  if (x &lt; 0)
    throw(NegativeLogValueException(value=x))
  else
    log(x, base=base)
}


# Note that the order of the catch list is important:
l &lt;- NA
x &lt;- 123
tryCatch({
  l &lt;- mylog(x)
}, NegativeLogValueException = function(ex) {
  cat(as.character(ex), "\n")
}, "try-error" = function(ex) {
  cat("try-error: Could not calculate the logarithm of ", x, ".\n", sep="")
}, error = function(ex) {
  cat("error: Could not calculate the logarithm of ", x, ".\n", sep="")
})
cat("The logarithm of ", x, " is ", l, ".\n\n", sep="")

</code></pre>


</div>